packages:
  - packages/**
  - examples
  - example-ssr
catalog:
  '@antfu/eslint-config': ^4.19.0
  '@types/node': ^22.17.2
  '@types/throttle-debounce': ^5.0.2
  '@vitejs/plugin-vue': ^5.2.4
  cpy: ^11.1.0
  element-plus: ^2.10.4
  eslint: ^9.33.0
  fast-glob: ^3.3.3
  nuxt: ^4.1.0
  sass: ^1.90.0
  throttle-debounce: ^5.0.2
  typescript: ^5.9.2
  unplugin-auto-import: ^19.3.0
  unplugin-vue-components: ^28.8.0
  vite: ^6.3.5
  vite-plugin-dts: ^4.3.0
  vue: ^3.5.21
  vue-router: ^4.5.1
  vue-tsc: ^2.2.12
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
